version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/tauri-app"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "pip"
    directory: "/python-backend"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "cargo"
    directory: "/tauri-app/src-tauri"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
